version: '3'
services:
  web:
    environment:
      - WATCHPACK_POLLING=true
    image: darcksoul/my-app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    environment:
      - WATCHPACK_POLLING=true
    image: darcksoul/my-app
    volumes:
      - /app/node_modules
      - .:/app
    command: ['yarn', 'test']